- check:
    from: sender@example.com
    subject_regex:
      - (?P<year>\d{4})
      - -(?P<month>\d{2})
      - -(?P<day>\d{2})
      - T(?P<hour>\d{2})
      - (?P<minute>\d{2})
      - \.csv

  save_file_format: >
    {year}-{month}-{day}T{hour}{minute}.csv
