- check:
    from: sender@example.com
    subject_regex:
      - (?P<year>\d{4})
      - -(?P<month>\d{2})
      - -(?P<day>\d{2})
      - T(?P<hour>\d{2})
      - (?P<minute>\d{2})
      - \.csv

  load_csv:
    columns:
      sensor1:
        type: float
      sensor2:
        type: int
      sensor3:
        type: text

    date_time:
      column: datetime
      format: >
        %Y-%m-%dT%H:%M:%S

    latitude:
      column: latitude

    longitude:
      column: longitude

  save_csv:
    file_name_format: >
      {year}-{month}-{day}T{hour}{minute}.csv

  save_table:
    file_name_format: >
      voyage_{year}{month}{day}
